In [3]:
import pandas as pd

In [49]:
datatest = pd.read_csv(
    'netflixmoviedb.csv',
    engine='python',
    encoding='utf-8',
    on_bad_lines='skip'
)

In [5]:
datatest.head

<bound method NDFrame.head of      Release_Date                                 Title  \
0      2021-12-15               Spider-Man: No Way Home
1      2022-03-01                            The Batman
2      2022-02-25                               No Exit
3      2021-11-24                               Encanto
4      2021-12-22                        The King's Man
...           ...                                   ...
9832   1973-10-15                              Badlands
9833   2020-10-01                      Violent Delights
9834   2016-05-06                          The Offering
9835   2021-03-31  The United States vs. Billie Holiday
9836   1984-09-23                               Threads

                                               Overview  Popularity  \
0     Peter Parker is unmasked and no longer able to...    5083.954
1     In his second year of fighting crime, Batman u...    3827.658
2     Stranded at a rest stop in the mountains durin...    2618.087
3     The tale of an extraordinary family, the Madri...    2402.201
4     As a collection of history's worst tyrants and...    1895.511
...                                                 ...         ...
9832  A dramatization of the Starkweather-Fugate kil...      13.357
9833  A female vampire falls in love with a man she ...      13.356
9834  When young and successful reporter Jamie finds...      13.355
9835  Billie Holiday spent much of her career being ...      13.354
9836  Documentary style account of a nuclear holocau...      13.354

     Vote_Count Vote_Average Original_Language  \
0          8940          8.3                en
1          1151          8.1                en
2           122          6.3                en
3          5076          7.7                en
4          1793          7.0                en
...         ...          ...               ...
9832        896          7.6                en
9833          8          3.5                es
9834         94          5.0                en
9835        152          6.7                en
9836        186          7.8                en

                                   Genre  \
0     Action, Adventure, Science Fiction
1               Crime, Mystery, Thriller
2                               Thriller
3     Animation, Comedy, Family, Fantasy
4       Action, Adventure, Thriller, War
...                                  ...
9832                        Drama, Crime
9833                              Horror
9834           Mystery, Thriller, Horror
9835               Music, Drama, History
9836         War, Drama, Science Fiction

                                             Poster_Url
0     https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1     https://image.tmdb.org/t/p/original/74xTEgt7R3...
2     https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3     https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4     https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
...                                                 ...
9832  https://image.tmdb.org/t/p/original/z81rBzHNgi...
9833  https://image.tmdb.org/t/p/original/4b6HY7rud6...
9834  https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9835  https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9836  https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

[9837 rows x 9 columns]>

In [6]:
datatest.dtypes

Release_Date             str
Title                    str
Overview                 str
Popularity           float64
Vote_Count               str
Vote_Average             str
Original_Language        str
Genre                    str
Poster_Url               str
dtype: object

In [7]:
datatest['Release_Date'] = pd.to_datetime(
    datatest['Release_Date'],
    errors='coerce'
).dt.date

In [8]:
datatest.dtypes

Release_Date          object
Title                    str
Overview                 str
Popularity           float64
Vote_Count               str
Vote_Average             str
Original_Language        str
Genre                    str
Poster_Url               str
dtype: object

In [9]:
datatest['Release_Date'] = pd.to_datetime(
    datatest['Release_Date'],
    errors='coerce'
)

In [10]:
datatest.dtypes

Release_Date         datetime64[s]
Title                          str
Overview                       str
Popularity                 float64
Vote_Count                     str
Vote_Average                   str
Original_Language              str
Genre                          str
Poster_Url                     str
dtype: object

In [11]:
datatest['Release_Year'] = datatest['Release_Date'].dt.year

In [12]:
datatest[['Release_Date', 'Release_Year']].head()

  Release_Date  Release_Year
0   2021-12-15        2021.0
1   2022-03-01        2022.0
2   2022-02-25        2022.0
3   2021-11-24        2021.0
4   2021-12-22        2021.0

In [40]:
datatest['Release_Year'] = datatest['Release_Year'].astype('Int64')

In [32]:
datatest.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,Release_Year
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021

In [50]:
print(datatest['Vote_Average'].dtype)
print(datatest['Vote_Average'].head())

str
0    8.3
1    8.1
2    6.3
3    7.7
4    7.0
Name: Vote_Average, dtype: str

In [52]:
def categorize_col(df, col, labels):
    col_min  = df[col].min()
    col_25   = df[col].quantile(0.25)
    col_50   = df[col].quantile(0.50)
    col_75   = df[col].quantile(0.75)
    col_max  = df[col].max()

    edges = [col_min, col_25, col_50, col_75, col_max]
    df[col] = pd.cut(df[col], bins=edges, labels=labels, include_lowest=True)
    return df

In [53]:
labels = ['not_popular', 'below_avg', 'average', 'popular']

if datatest['Vote_Average'].dtype != 'category':
    categorize_col(datatest, 'Vote_Average', labels)

datatest['Vote_Average'].unique()

['popular', 'below_avg', 'average', 'not_popular', NaN]
Categories (4, str): ['not_popular' < 'below_avg' < 'average' < 'popular']

In [51]:
datatest['Vote_Average'] = pd.to_numeric(datatest['Vote_Average'], errors='coerce')

In [54]:
datatest.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,popular,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,popular,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,below_avg,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,popular,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,average,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...